CREATE TABLE `clientLeads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32),
	`businessName` varchar(256) NOT NULL,
	`industry` varchar(128),
	`websiteUrl` varchar(2048),
	`facebookUrl` varchar(2048),
	`instagramUrl` varchar(2048),
	`tiktokUrl` varchar(2048),
	`linkedinUrl` varchar(2048),
	`youtubeUrl` varchar(2048),
	`facebookFollowers` int,
	`instagramFollowers` int,
	`tiktokFollowers` int,
	`monthlyBudget` varchar(64),
	`primaryGoal` varchar(256),
	`currentChallenges` text,
	`targetAudience` text,
	`aiAnalysis` text,
	`aiStrategy` text,
	`proposedPricing` varchar(128),
	`analysisScore` int,
	`status` enum('submitted','analysing','proposal_sent','approved','rejected','active') NOT NULL DEFAULT 'submitted',
	`proposalSentAt` timestamp,
	`approvedAt` timestamp,
	`inviteToken` varchar(128),
	`inviteExpiresAt` timestamp,
	`linkedUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clientLeads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `clientPortalSessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`token` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`expiresAt` timestamp NOT NULL,
	`lastAccessedAt` timestamp,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `clientPortalSessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `clientPortalSessions_token_unique` UNIQUE(`token`)
);
