import type { Agent } from "./supabase/types";

export const AGENTS: Agent[] = [
  {
    id: "naledi-001",
    name: "Naledi",
    codename: "NALEDI-CMO",
    role: "Content Chief Marketing Officer",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 634,
    current_task: "Generating Instagram content for Father's Day campaign",
    avatar_color: "#ff00ff",
  },
  {
    id: "charlie-002",
    name: "Charlie",
    codename: "CHARLIE-OPS",
    role: "Fulfillment & Operations Orchestrator",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 1247,
    current_task: "Processing studexmeat.com orders (28 pending)",
    avatar_color: "#ff2d78",
  },
  {
    id: "opencode-003",
    name: "OpenCode",
    codename: "OPENCODE-SYS",
    role: "Systems & Integration Manager",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 892,
    current_task: "Syncing Notion database with customer records",
    avatar_color: "#00f0ff",
  },
  {
    id: "robusca-004",
    name: "Robusca",
    codename: "ROBUSCA-STAFF",
    role: "Chief of Staff & Orchestrator",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 756,
    current_task: "Preparing 10 AM board meeting agenda",
    avatar_color: "#00ff88",
  },
  {
    id: "tumelo-005",
    name: "Tumelo",
    codename: "TUMELO-LORD",
    role: "Agent Lord & Founder",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 1823,
    current_task: "Reviewing strategic decisions for board meeting",
    avatar_color: "#ffd700",
  },
  {
    id: "zara-006",
    name: "Zara",
    codename: "ZARA-CONTENT",
    role: "Content Strategist",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 421,
    current_task: "Planning weekly content calendar",
    avatar_color: "#ff7700",
  },
  {
    id: "kai-007",
    name: "Kai",
    codename: "KAI-ANALYTICS",
    role: "Analytics & Insights",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 567,
    current_task: "Analyzing Meta Ads ROAS metrics",
    avatar_color: "#0088ff",
  },
  {
    id: "luna-008",
    name: "Luna",
    codename: "LUNA-GROWTH",
    role: "Growth & Customer Acquisition",
    status: "processing",
    last_active: new Date().toISOString(),
    tasks_completed: 345,
    current_task: "Optimizing Google Ads campaigns",
    avatar_color: "#ff00aa",
  },
  {
    id: "axel-009",
    name: "Axel",
    codename: "AXEL-FINANCE",
    role: "Finance & Budget Manager",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 523,
    current_task: "Reconciling daily revenue reports",
    avatar_color: "#88ff00",
  },
  {
    id: "iris-010",
    name: "Iris",
    codename: "IRIS-CUSTOMER",
    role: "Customer Support & Community",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 892,
    current_task: "Handling customer inquiries via WhatsApp",
    avatar_color: "#00ffff",
  },
  {
    id: "remi-011",
    name: "Remi",
    codename: "REMI-QUALITY",
    role: "Quality Assurance & Testing",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 612,
    current_task: "Testing new Dark Factory features",
    avatar_color: "#ff6699",
  },
  {
    id: "nova-012",
    name: "Nova",
    codename: "NOVA-RESEARCH",
    role: "Research & Development",
    status: "processing",
    last_active: new Date().toISOString(),
    tasks_completed: 234,
    current_task: "Researching AI model optimization",
    avatar_color: "#99ff00",
  },
  {
    id: "sage-013",
    name: "Sage",
    codename: "SAGE-MENTOR",
    role: "Agent Training & Mentorship",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 445,
    current_task: "Training new agents on system protocols",
    avatar_color: "#00ff99",
  },
  {
    id: "vex-014",
    name: "Vex",
    codename: "VEX-SECURITY",
    role: "Security & Compliance",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 567,
    current_task: "Monitoring security logs and alerts",
    avatar_color: "#ff0099",
  },
  {
    id: "echo-015",
    name: "Echo",
    codename: "ECHO-SYNC",
    role: "Data Synchronization & Backup",
    status: "online",
    last_active: new Date().toISOString(),
    tasks_completed: 723,
    current_task: "Syncing data across 10 environments",
    avatar_color: "#9900ff",
  },
];

export function getAgent(id: string): Agent | undefined {
  return AGENTS.find((a) => a.id === id || a.name.toLowerCase() === id.toLowerCase());
}
