import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import { getDb } from "../db";
import { analyses } from "../../drizzle/schema";
import { eq, and } from "drizzle-orm";
import { storagePut } from "../storage";

// ─── PDF Generation using reportlab-style approach ───────────────────────────
async function generatePdfFromMarkdown(markdown: string, domain: string): Promise<Buffer> {
  // Use a simple HTML-to-PDF approach via built-in Node.js
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a2e; line-height: 1.6; }
  h1 { color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
  h2 { color: #1e1b4b; margin-top: 30px; }
  h3 { color: #312e81; }
  table { width: 100%; border-collapse: collapse; margin: 15px 0; }
  th { background: #4f46e5; color: white; padding: 8px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) { background: #f8fafc; }
  code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; }
  blockquote { border-left: 4px solid #4f46e5; margin: 15px 0; padding: 10px 20px; background: #f8fafc; }
  .header { background: linear-gradient(135deg, #4f46e5, #7c3aed); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px; }
  .header h1 { color: white; border-bottom: 1px solid rgba(255,255,255,0.3); }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; text-align: center; }
</style>
</head>
<body>
<div class="header">
  <h1>Business Intelligence Report</h1>
  <p>Domain: ${domain} | Generated: ${new Date().toLocaleDateString()}</p>
</div>
${markdownToHtml(markdown)}
<div class="footer">
  <p>Generated by Nexus Social Intelligence Platform | ${new Date().toISOString()}</p>
</div>
</body>
</html>`;

  // Return HTML as buffer (in production this would use puppeteer/wkhtmltopdf)
  return Buffer.from(html, "utf-8");
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/^\| (.+) \|$/gm, (match) => {
      const cells = match.split("|").filter(c => c.trim());
      return "<tr>" + cells.map(c => `<td>${c.trim()}</td>`).join("") + "</tr>";
    })
    .replace(/(<tr>.*<\/tr>\n?)+/g, (match) => `<table>${match}</table>`)
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`)
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    .replace(/^---$/gm, "<hr>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[h|t|u|l|h])/gm, "")
    .replace(/\n/g, "<br>");
}

export const exportRouter = router({
  // Generate and download PDF report
  generatePdf: protectedProcedure
    .input(z.object({ analysisId: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error("Database unavailable");

      const [analysis] = await db.select().from(analyses)
        .where(and(eq(analyses.id, input.analysisId), eq(analyses.userId, ctx.user.id)))
        .limit(1);

      if (!analysis) throw new Error("Analysis not found");
      if (!analysis.reportMarkdown) throw new Error("Report not yet generated");

      const pdfBuffer = await generatePdfFromMarkdown(analysis.reportMarkdown, analysis.domain);

      // Upload to S3
      const key = `reports/${ctx.user.id}/${analysis.domain}-${Date.now()}.html`;
      const { url } = await storagePut(key, pdfBuffer, "text/html");

      // Update analysis with report URL
      await db.update(analyses).set({ reportPdfUrl: url }).where(eq(analyses.id, input.analysisId));

      return { url, filename: `${analysis.domain}-report.html` };
    }),

  // Export to Google Drive (returns markdown content for manual upload)
  exportToGoogleDrive: protectedProcedure
    .input(z.object({ analysisId: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error("Database unavailable");

      const [analysis] = await db.select().from(analyses)
        .where(and(eq(analyses.id, input.analysisId), eq(analyses.userId, ctx.user.id)))
        .limit(1);

      if (!analysis) throw new Error("Analysis not found");
      if (!analysis.reportMarkdown) throw new Error("Report not yet generated");

      // Store the markdown report in S3 for download
      const dateStr = new Date().toISOString().split("T")[0];
      const key = `drive-exports/${ctx.user.id}/${dateStr}/${analysis.domain}-report.md`;
      const { url } = await storagePut(key, Buffer.from(analysis.reportMarkdown, "utf-8"), "text/markdown");

      // Update analysis with Google Drive URL placeholder
      await db.update(analyses).set({ googleDriveUrl: url }).where(eq(analyses.id, input.analysisId));

      return {
        url,
        filename: `${analysis.domain}-report.md`,
        instructions: "Download this file and upload it to your Google Drive folder. For automatic Google Drive sync, connect your Google account in Settings.",
        content: analysis.reportMarkdown,
      };
    }),

  // Get export status for an analysis
  getExportStatus: protectedProcedure
    .input(z.object({ analysisId: z.number() }))
    .query(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new Error("Database unavailable");

      const [analysis] = await db.select({
        reportPdfUrl: analyses.reportPdfUrl,
        googleDriveUrl: analyses.googleDriveUrl,
        domain: analyses.domain,
      }).from(analyses)
        .where(and(eq(analyses.id, input.analysisId), eq(analyses.userId, ctx.user.id)))
        .limit(1);

      return analysis || null;
    }),
});
